# Generated by Django 4.2.1 on 2023-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='email',
        ),
    ]
