# Generated by Django 4.2.1 on 2023-06-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tenant',
            name='auth0_tenant_id',
            field=models.CharField(default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenant.tenant'),
        ),
        migrations.AlterModelTable(
            name='tenant',
            table=None,
        ),
    ]
